//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EM_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgressPhoto
    {
        public int pid { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string caption { get; set; }
        public Nullable<int> uid { get; set; }
        public string photo { get; set; }
    
        public virtual User User { get; set; }
    }
}
