//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EM_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EM_Entities : DbContext
    {
        public EM_Entities()
            : base("name=EM_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ProgressPhoto> ProgressPhotos { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<exerciseLog> exerciseLogs { get; set; }
        public DbSet<wrongPoseLog> wrongPoseLogs { get; set; }
    }
}
