//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EM_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.ProgressPhotos = new HashSet<ProgressPhoto>();
        }
    
        public int uid { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string profilePic { get; set; }
        public string gender { get; set; }
        public string age { get; set; }
        public string height { get; set; }
        public string weight { get; set; }
        public string bmi { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<ProgressPhoto> ProgressPhotos { get; set; }
    }
}
