//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EM_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wrongPoseLog
    {
        public int wrngPoseId { get; set; }
        public int uid { get; set; }
        public Nullable<int> atRep { get; set; }
        public string wrongPosePic { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public string direction { get; set; }
        public string exerciseName { get; set; }
        public string angleOne { get; set; }
        public string angleTwo { get; set; }
        public string wrongAngleOne { get; set; }
        public string wrongAngleTwo { get; set; }
        public string correctAngleOne { get; set; }
        public string correctAngleTwo { get; set; }
        public string bodyAngle { get; set; }
        public string vertix1 { get; set; }
        public string vertix2 { get; set; }
        public string vertix3 { get; set; }
        public string vertix4 { get; set; }
        public string vertix5 { get; set; }
    }
}
